# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sakshamvitwekar/CRAW

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sakshamvitwekar/CRAW

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sakshamvitwekar/CRAW/CMakeFiles /home/sakshamvitwekar/CRAW//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sakshamvitwekar/CRAW/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/sakshamvitwekar/CRAW/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CRAW

# Build rule for target.
CRAW: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CRAW
.PHONY : CRAW

# fast build rule for target.
CRAW/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/build
.PHONY : CRAW/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

examples/getTopPosts.o: examples/getTopPosts.c.o
.PHONY : examples/getTopPosts.o

# target to build an object file
examples/getTopPosts.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/examples/getTopPosts.c.o
.PHONY : examples/getTopPosts.c.o

examples/getTopPosts.i: examples/getTopPosts.c.i
.PHONY : examples/getTopPosts.i

# target to preprocess a source file
examples/getTopPosts.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/examples/getTopPosts.c.i
.PHONY : examples/getTopPosts.c.i

examples/getTopPosts.s: examples/getTopPosts.c.s
.PHONY : examples/getTopPosts.s

# target to generate assembly for a file
examples/getTopPosts.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/examples/getTopPosts.c.s
.PHONY : examples/getTopPosts.c.s

src/CRAW_Account.o: src/CRAW_Account.c.o
.PHONY : src/CRAW_Account.o

# target to build an object file
src/CRAW_Account.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Account.c.o
.PHONY : src/CRAW_Account.c.o

src/CRAW_Account.i: src/CRAW_Account.c.i
.PHONY : src/CRAW_Account.i

# target to preprocess a source file
src/CRAW_Account.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Account.c.i
.PHONY : src/CRAW_Account.c.i

src/CRAW_Account.s: src/CRAW_Account.c.s
.PHONY : src/CRAW_Account.s

# target to generate assembly for a file
src/CRAW_Account.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Account.c.s
.PHONY : src/CRAW_Account.c.s

src/CRAW_Links.o: src/CRAW_Links.c.o
.PHONY : src/CRAW_Links.o

# target to build an object file
src/CRAW_Links.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Links.c.o
.PHONY : src/CRAW_Links.c.o

src/CRAW_Links.i: src/CRAW_Links.c.i
.PHONY : src/CRAW_Links.i

# target to preprocess a source file
src/CRAW_Links.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Links.c.i
.PHONY : src/CRAW_Links.c.i

src/CRAW_Links.s: src/CRAW_Links.c.s
.PHONY : src/CRAW_Links.s

# target to generate assembly for a file
src/CRAW_Links.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Links.c.s
.PHONY : src/CRAW_Links.c.s

src/CRAW_Listing.o: src/CRAW_Listing.c.o
.PHONY : src/CRAW_Listing.o

# target to build an object file
src/CRAW_Listing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Listing.c.o
.PHONY : src/CRAW_Listing.c.o

src/CRAW_Listing.i: src/CRAW_Listing.c.i
.PHONY : src/CRAW_Listing.i

# target to preprocess a source file
src/CRAW_Listing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Listing.c.i
.PHONY : src/CRAW_Listing.c.i

src/CRAW_Listing.s: src/CRAW_Listing.c.s
.PHONY : src/CRAW_Listing.s

# target to generate assembly for a file
src/CRAW_Listing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Listing.c.s
.PHONY : src/CRAW_Listing.c.s

src/CRAW_Main.o: src/CRAW_Main.c.o
.PHONY : src/CRAW_Main.o

# target to build an object file
src/CRAW_Main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Main.c.o
.PHONY : src/CRAW_Main.c.o

src/CRAW_Main.i: src/CRAW_Main.c.i
.PHONY : src/CRAW_Main.i

# target to preprocess a source file
src/CRAW_Main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Main.c.i
.PHONY : src/CRAW_Main.c.i

src/CRAW_Main.s: src/CRAW_Main.c.s
.PHONY : src/CRAW_Main.s

# target to generate assembly for a file
src/CRAW_Main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Main.c.s
.PHONY : src/CRAW_Main.c.s

src/CRAW_Message.o: src/CRAW_Message.c.o
.PHONY : src/CRAW_Message.o

# target to build an object file
src/CRAW_Message.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Message.c.o
.PHONY : src/CRAW_Message.c.o

src/CRAW_Message.i: src/CRAW_Message.c.i
.PHONY : src/CRAW_Message.i

# target to preprocess a source file
src/CRAW_Message.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Message.c.i
.PHONY : src/CRAW_Message.c.i

src/CRAW_Message.s: src/CRAW_Message.c.s
.PHONY : src/CRAW_Message.s

# target to generate assembly for a file
src/CRAW_Message.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Message.c.s
.PHONY : src/CRAW_Message.c.s

src/CRAW_PRIVATE.o: src/CRAW_PRIVATE.c.o
.PHONY : src/CRAW_PRIVATE.o

# target to build an object file
src/CRAW_PRIVATE.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_PRIVATE.c.o
.PHONY : src/CRAW_PRIVATE.c.o

src/CRAW_PRIVATE.i: src/CRAW_PRIVATE.c.i
.PHONY : src/CRAW_PRIVATE.i

# target to preprocess a source file
src/CRAW_PRIVATE.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_PRIVATE.c.i
.PHONY : src/CRAW_PRIVATE.c.i

src/CRAW_PRIVATE.s: src/CRAW_PRIVATE.c.s
.PHONY : src/CRAW_PRIVATE.s

# target to generate assembly for a file
src/CRAW_PRIVATE.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_PRIVATE.c.s
.PHONY : src/CRAW_PRIVATE.c.s

src/CRAW_Subreddit.o: src/CRAW_Subreddit.c.o
.PHONY : src/CRAW_Subreddit.o

# target to build an object file
src/CRAW_Subreddit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Subreddit.c.o
.PHONY : src/CRAW_Subreddit.c.o

src/CRAW_Subreddit.i: src/CRAW_Subreddit.c.i
.PHONY : src/CRAW_Subreddit.i

# target to preprocess a source file
src/CRAW_Subreddit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Subreddit.c.i
.PHONY : src/CRAW_Subreddit.c.i

src/CRAW_Subreddit.s: src/CRAW_Subreddit.c.s
.PHONY : src/CRAW_Subreddit.s

# target to generate assembly for a file
src/CRAW_Subreddit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/CRAW_Subreddit.c.s
.PHONY : src/CRAW_Subreddit.c.s

src/cJSON.o: src/cJSON.c.o
.PHONY : src/cJSON.o

# target to build an object file
src/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/cJSON.c.o
.PHONY : src/cJSON.c.o

src/cJSON.i: src/cJSON.c.i
.PHONY : src/cJSON.i

# target to preprocess a source file
src/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/cJSON.c.i
.PHONY : src/cJSON.c.i

src/cJSON.s: src/cJSON.c.s
.PHONY : src/cJSON.s

# target to generate assembly for a file
src/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRAW.dir/build.make CMakeFiles/CRAW.dir/src/cJSON.c.s
.PHONY : src/cJSON.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... CRAW"
	@echo "... test"
	@echo "... examples/getTopPosts.o"
	@echo "... examples/getTopPosts.i"
	@echo "... examples/getTopPosts.s"
	@echo "... src/CRAW_Account.o"
	@echo "... src/CRAW_Account.i"
	@echo "... src/CRAW_Account.s"
	@echo "... src/CRAW_Links.o"
	@echo "... src/CRAW_Links.i"
	@echo "... src/CRAW_Links.s"
	@echo "... src/CRAW_Listing.o"
	@echo "... src/CRAW_Listing.i"
	@echo "... src/CRAW_Listing.s"
	@echo "... src/CRAW_Main.o"
	@echo "... src/CRAW_Main.i"
	@echo "... src/CRAW_Main.s"
	@echo "... src/CRAW_Message.o"
	@echo "... src/CRAW_Message.i"
	@echo "... src/CRAW_Message.s"
	@echo "... src/CRAW_PRIVATE.o"
	@echo "... src/CRAW_PRIVATE.i"
	@echo "... src/CRAW_PRIVATE.s"
	@echo "... src/CRAW_Subreddit.o"
	@echo "... src/CRAW_Subreddit.i"
	@echo "... src/CRAW_Subreddit.s"
	@echo "... src/cJSON.o"
	@echo "... src/cJSON.i"
	@echo "... src/cJSON.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/sakshamvitwekar/CRAW/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

