name: CRAW CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libcurl4-openssl-dev valgrind

    - name: Build project
      run: |
        cmake .
        make

    - name: Run example / test
      run: |
        ./test || true

    - name: Run valgrind
      run: |
        valgrind --leak-check=full ./test || true
